---

collections:
  - src: https://github.com/stackhpc/ansible-collection-azimuth-ops.git
    type: git
    version: etcd-volume-values
  # For local development
  # - type: dir
  #   source: ../ansible-collection-azimuth-ops
